### ISSUE TITLE
Add to awesome-textpattern

### ISSUE THREAD

**Issue by drmonkeyninja** [spiffin/spf_js#1]
If spf_js works with the current version of Textpattern (v4.5.7) please feel free to add it to https://github.com/drmonkeyninja/awesome-textpattern.

**Comment by spiffin** [comment]
Hi Andy

Thanks for your message. Unfortunately I can't read it on GitHub (it's
hidden for some reason).

Both spf_js and spf_codemirror work fine with Textpattern 4.5.7. Could you
tell me what to do? Do I fork awesome-textpattern, add my repos and then
issue a pull-request?

I use GitHub for personal projects only - so I'm not too up on git
collaboration.

Thanks,

Simon

**Comment by drmonkeyninja** [comment]
Hi Simon,

You've pretty much hit the nail on the head.
1. Create a fork of the awesome-textpattern repository.
2. Make your changes to the README.textile file and commit them.
3. Create a pull request from your forked repository.

Thanks

**Comment by spiffin** [comment]
Thanks Andy, all done.

Simon

**Comment by drmonkeyninja** [comment]
Thanks.
